### ISSUE TITLE
error: unable to recognize "daemon.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by csautter** [bowei/k8s-custom-iptables#13]
There are issues with daemon.yaml.
````bash
$ TARGETS="10.48.50.8/29" ./install.sh
configmap/k8s-custom-iptables unchanged
error: unable to recognize "daemon.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
````
https://github.com/bowei/k8s-custom-iptables/pull/12 -> fixes the Problem for me.

**Comment by pradeepnss** [comment]
This could be due api deprecation in k8s 1.16 and above where deamonsets api version should be apps/v1 instead of extensions/v1beta1 which is deprecated

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by danopia** [comment]
Looks like #12 has been merged for some time now, this can likely be closed?
