### ISSUE TITLE
what does the TARGETS env var do?

### ISSUE THREAD

**Issue by Lutando** [bowei/k8s-custom-iptables#5]
I am trying to get custom ip tables to work for Google Memorystore from my non IP-Aliased k8s cluster.

Do I put TARGETS="{cluster CIDR} {MemoryStore CIDR}"

eg

```
TARGETS="10.0.0.0/29 10.78.0.0/14" 
```

or just 

```
TARGETS="10.0.0.0/29" 
```

where 10.78.0.0/14 is my cluster CIDR and 10.0.0.0/29 is my memorystore CIDR? 

I think im misunderstanding how it works

**Comment by bowei** [comment]
Hi -- I see you closed your comment. Were you able to figure out the answer?

**Comment by Lutando** [comment]
Not particularly. I was using this to get google memory store to work in my k8s cluster without having vpc-aliasing enabled. I gave up because I spent a few days on it and got nowhere, even with help from the community, so im still running my own redis pods in k8s on GKE (not ideal)

**Comment by santiarias** [comment]
@Lutando TARGETS="10.0.0.0/29"  should work, please verify that the network is the same for you kubernetes cluster and for your memory store.

That is likely the cause of your problem

**Comment by bowei** [comment]
@Lutando -- @santiarias 's comment is correct.
